# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: NONE

version = 1

[[annotations]]
path = [
    "Cargo.lock",
    "POWER.txt",
]
precedence = "override"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "NONE"

[[annotations]]
path = [
    "Makefile",
    "README.md",
    "docs/**",
    "scripts/**",
    "src/**",
]
precedence = "override"
SPDX-License-Identifier = "GPL-3.0-only"
SPDX-FileCopyrightText = [
    "2025 System76, Inc.",
    "2020 Evan Lojewski",
    "2020 Fabian Topfstedt",
    "2020 Andrew Rodland",
    "2020 Brosseau Valentin",
    "2023 3mdeb Sp. z o.o.",
]
