# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: NONE

version = 1

[[annotations]]
path = [
    "Makefile",
    "README.md",
    "src/**",
]
precedence = "override"
SPDX-License-Identifier = "GPL-3.0-only"
SPDX-FileCopyrightText = "2025 System76, Inc."
